on: [push, pull_request]
name: ubuntu

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: bazelbuild/setup-bazelisk@v2

    - name: Test
      run: bazel run test --enable_platform_specific_config
